"""Golden cross-check against the Voice Memory paper's original implementation.

The expected values below were generated by running the paper's reference code
(``skillopt_asr/metrics.py`` + ``skillopt_asr/harmful_edit.py``, the exact
implementation behind the published tables) on this fixed corpus. agwer with
default settings must reproduce them bit-for-bit in spirit (float-approx).
"""

import pytest

import agwer

CORPUS = [
    ("the quick brown fox jumps",
     ["the quick brown fox jump", "the quick brown fox jumps", "a quick brown fox jump",
      "the quik brown fox jump", "the quick brown fox"],
     "the quick brown fox jumps"),
    ("she sells sea shells",
     ["she sells sea shells", "she sell sea shells", "she sells see shells",
      "she sells sea shell", "sea sells sea shells"],
     "she sells seashells"),
    ("hello world",
     ["hello world", "hello word", "jello world", "hello world", "hello whirled"],
     "hello world"),
    ("meet me at noon",
     ["meet me at soon", "meet me at moon", "meat me at noon",
      "meet me at noon", "meet my at noon"],
     "meet me at night"),
    ("numbers like forty two",
     ["numbers like forty too", "numbers like four two", "number like forty two",
      "numbers like forty two", "numbers likes forty two"],
     "numbers like 42"),
]

REFS = [c[0] for c in CORPUS]
NBEST = [c[1] for c in CORPUS]
CORRECTED = [c[2] for c in CORPUS]

# --- golden values from the paper's reference implementation ---
GOLD_WER_1BEST = 0.15789473684210525
GOLD_WER_ORACLE = 0.0
GOLD_WER_CORRECTED = 0.2631578947368421
GOLD_RHO = -0.6666666666666666
GOLD_HER = 0.6666666666666666
GOLD_CATEGORIES = {"helpful": 1, "harmful": 2, "neutral": 1, "no_edit": 1}
GOLD_ORACLE_PICKS = [
    "the quick brown fox jumps",
    "she sells sea shells",
    "hello world",
    "meet me at noon",
    "numbers like forty two",
]


def test_reproduces_reference_implementation():
    out = agwer.evaluate(REFS, CORRECTED, nbest=NBEST)
    assert out.wer_1best == pytest.approx(GOLD_WER_1BEST)
    assert out.wer_oracle == pytest.approx(GOLD_WER_ORACLE)
    assert out.wer_corrected == pytest.approx(GOLD_WER_CORRECTED)
    assert out.rir == pytest.approx(GOLD_RHO)
    assert out.her == pytest.approx(GOLD_HER)
    assert out.edits.helpful == GOLD_CATEGORIES["helpful"]
    assert out.edits.harmful == GOLD_CATEGORIES["harmful"]
    assert out.edits.neutral == GOLD_CATEGORIES["neutral"]
    assert out.edits.no_edit == GOLD_CATEGORIES["no_edit"]


def test_reproduces_reference_oracle_selection():
    assert agwer.oracle_hypotheses(REFS, NBEST) == GOLD_ORACLE_PICKS
